// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Client {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// "franka", "ur5", "sim"
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tensor {
    /// "camera/wrist", "proprioception"
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(enumeration = "DType", tag = "2")]
    pub dtype: i32,
    #[prost(int64, repeated, tag = "3")]
    pub shape: ::prost::alloc::vec::Vec<i64>,
    #[prost(uint64, tag = "4")]
    pub byte_offset: u64,
    #[prost(uint64, tag = "5")]
    pub byte_length: u64,
    /// per-tensor temporal alignment
    #[prost(uint64, tag = "6")]
    pub timestamp_ns: u64,
    #[prost(enumeration = "Encoding", tag = "7")]
    pub encoding: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Observation {
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<Client>,
    #[prost(uint64, tag = "2")]
    pub timestamp_ns: u64,
    /// 0.0 (low) to 1.0 (critical)
    #[prost(float, tag = "3")]
    pub urgency: f32,
    #[prost(message, repeated, tag = "4")]
    pub tensors: ::prost::alloc::vec::Vec<Tensor>,
    #[prost(string, tag = "5")]
    pub model_id: ::prost::alloc::string::String,
    /// optional hint from robot
    #[prost(uint32, optional, tag = "6")]
    pub steps_remaining: ::core::option::Option<u32>,
    #[prost(map = "string, string", tag = "7")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 0 = highest priority
    #[prost(uint32, tag = "8")]
    pub priority: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelResponse {
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<Client>,
    #[prost(string, tag = "2")]
    pub response_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub timestamp_ns: u64,
    #[prost(message, repeated, tag = "4")]
    pub tensors: ::prost::alloc::vec::Vec<Tensor>,
    #[prost(float, tag = "5")]
    pub inference_latency_ms: f32,
    #[prost(string, tag = "6")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "7")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DType {
    DtypeUnspecified = 0,
    Float16 = 1,
    Float32 = 2,
    Float64 = 3,
    Bfloat16 = 4,
    Uint8 = 5,
    Int32 = 6,
    Int64 = 7,
    Bool = 8,
}
impl DType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DtypeUnspecified => "DTYPE_UNSPECIFIED",
            Self::Float16 => "FLOAT16",
            Self::Float32 => "FLOAT32",
            Self::Float64 => "FLOAT64",
            Self::Bfloat16 => "BFLOAT16",
            Self::Uint8 => "UINT8",
            Self::Int32 => "INT32",
            Self::Int64 => "INT64",
            Self::Bool => "BOOL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DTYPE_UNSPECIFIED" => Some(Self::DtypeUnspecified),
            "FLOAT16" => Some(Self::Float16),
            "FLOAT32" => Some(Self::Float32),
            "FLOAT64" => Some(Self::Float64),
            "BFLOAT16" => Some(Self::Bfloat16),
            "UINT8" => Some(Self::Uint8),
            "INT32" => Some(Self::Int32),
            "INT64" => Some(Self::Int64),
            "BOOL" => Some(Self::Bool),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Encoding {
    Unspecified = 0,
    Raw = 1,
    Jpeg = 2,
    Png = 3,
}
impl Encoding {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENCODING_UNSPECIFIED",
            Self::Raw => "RAW",
            Self::Jpeg => "JPEG",
            Self::Png => "PNG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENCODING_UNSPECIFIED" => Some(Self::Unspecified),
            "RAW" => Some(Self::Raw),
            "JPEG" => Some(Self::Jpeg),
            "PNG" => Some(Self::Png),
            _ => None,
        }
    }
}
